# Pytorch Basics

#### Requirements
python​​3.x\
vscode or jupyter notebook

#### Create Virtual Environment
python3 -m venv venv3\
source venv3/bin/activate​
#### Visit pytorch website and get pytorch install command.​

Web: https://pytorch.org/get-started/locally/​

In [1]:
# verify pytorch installation
import torch

In [2]:
print(torch.__version__)

1.13.1+cu117


#### A tensor of : Height = 2,  Width = 3

In [3]:
tensor_a = torch.tensor([[1, 2, 3], [4, 5, 6]])  # Two rows, three columns
print(tensor_a)

tensor([[1, 2, 3],
        [4, 5, 6]])


In [4]:
tensor_a.shape

torch.Size([2, 3])

A tensor of : Chanel = 3, Height = 2, Width = 1

In [5]:
tensor_b = torch.tensor(
    [[[1], [4]], [[1], [4]], [[1], [4]]]
)  # Three channels, two rows, one column

In [6]:
tensor_b

tensor([[[1],
         [4]],

        [[1],
         [4]],

        [[1],
         [4]]])

Axis 0, 1, 2

In [7]:
tensor_b.shape

torch.Size([3, 2, 1])

**We can also specify data type while creating tensor**

References: https://pytorch.org/docs/stable/tensors.html#data-types

In [8]:
tensor_a = torch.tensor(
    [[1, 2, 3], [4, 5, 6]], dtype=torch.float16
)  # two rows and three columns tensor with float16 values
print(tensor_a)

tensor([[1., 2., 3.],
        [4., 5., 6.]], dtype=torch.float16)


**We can also specify device type while creating tensor**

References: https://pytorch.org/docs/stable/tensor_attributes.html#torch-device

In [9]:
print(torch.cuda.is_available())

False


In [10]:
## usual practise is that we decide device in start

device = "cuda" if torch.cuda.is_available() else "cpu"
tensor_c = torch.tensor(
    [[1, 2, 3], [4, 5, 6]], dtype=torch.float32, device=device
)  # two rows and three columns tensor with float32 values on specified device

In [11]:
tensor_c

tensor([[1., 2., 3.],
        [4., 5., 6.]])

**Move tensor across devices**

In [12]:
device = "cuda" if torch.cuda.is_available() else "cpu"

In [13]:
tensor_a = torch.tensor([[1, 2, 3], [4, 5, 6]])
tensor_a = tensor_a.to(device)

#### Common Initialization methods:​

​
**Uninitialized data:**

reference: ​

https://pytorch.org/docs/stable/generated/torch.empty.html​

In [14]:
x = torch.empty(size=(10, 10))
print(x)

tensor([[ 1.4013e-44,  4.5743e-41, -3.4924e+14,  3.0773e-41,  1.5863e-42,
          2.6625e-44, -3.4925e+14,  3.0773e-41,  1.4013e-44,  0.0000e+00],
        [-3.4924e+14,  3.0773e-41,  1.5877e-42,  0.0000e+00, -3.4925e+14,
          3.0773e-41,  1.4013e-44,  0.0000e+00, -3.4925e+14,  3.0773e-41],
        [ 1.5891e-42,  0.0000e+00, -3.4925e+14,  3.0773e-41,  1.4013e-44,
          0.0000e+00, -3.4925e+14,  3.0773e-41,  1.5905e-42,  0.0000e+00],
        [-3.4925e+14,  3.0773e-41,  1.4013e-44,  0.0000e+00, -3.4925e+14,
          3.0773e-41,  1.5961e-42,  0.0000e+00, -3.4925e+14,  3.0773e-41],
        [ 1.4013e-44,  0.0000e+00, -3.4925e+14,  3.0773e-41,  2.8026e-44,
          0.0000e+00, -2.8314e+38,  4.5743e-41,  0.0000e+00,  0.0000e+00],
        [-3.4925e+14,  3.0773e-41,  1.4013e-45,  3.0829e-44,  1.4013e-45,
          3.3631e-44,  2.8026e-44,  0.0000e+00, -2.8314e+38,  4.5743e-41],
        [ 0.0000e+00,  0.0000e+00, -3.4925e+14,  3.0773e-41,  1.4013e-45,
          3.0829e-44,  1.4013e-4

**All zero data**

reference:
https://pytorch.org/docs/stable/generated/torch.zeros.html

In [15]:
x = torch.zeros(size=(10, 10))
print(x)

tensor([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])


**All ones data**​

reference: ​
https://pytorch.org/docs/stable/generated/torch.ones.html​​

In [16]:
x = torch.ones(size=(10, 10))
print(x)

tensor([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])


**All random numbers with uniform distribution between interval [0, 1)​**​​
​

References: ​

https://pytorch.org/docs/stable/generated/torch.rand.html​

​

In [17]:
x = torch.rand(size=(5, 5))
print(x)

tensor([[0.5527, 0.5512, 0.8526, 0.8328, 0.7476],
        [0.0975, 0.5877, 0.6356, 0.4042, 0.9845],
        [0.8052, 0.0486, 0.2180, 0.1083, 0.7497],
        [0.7274, 0.7963, 0.4496, 0.9178, 0.3041],
        [0.6591, 0.9026, 0.6019, 0.2236, 0.8022]])


**All random numbers with uniform distribution between with given mean and std dev​**

<b>NOTE: "_" after normal means that it is an inplace operation​</b>

References: ​

https://pytorch.org/docs/stable/generated/torch.rand.html​

In [18]:
x = torch.empty(size=(5, 5)).normal_(mean=0, std=2)
print(x)

tensor([[ 1.4775, -0.1794, -2.3660, -1.5134, -5.0399],
        [-1.9835,  5.2303,  1.3664,  1.1181, -3.9798],
        [-0.5099, -3.8679, -1.3637, -3.7752, -0.9410],
        [ 1.9416,  0.0572, -0.7178, -0.3660,  0.6043],
        [-0.2658, -3.7026, -0.6004,  0.5982,  0.2120]])


**Create evenly spaced values between given range​**

References:​

https://pytorch.org/docs/stable/generated/torch.linspace.html

In [19]:
# create list of 13 numbers between 1 to 54 which are evenly spaced
x = torch.linspace(start=1, end=54, steps=13)
print(x)

tensor([ 1.0000,  5.4167,  9.8333, 14.2500, 18.6667, 23.0833, 27.5000, 31.9167,
        36.3333, 40.7500, 45.1667, 49.5833, 54.0000])


**Identity matrix**​

reference: ​

https://pytorch.org/docs/stable/generated/torch.eye.html​

In [20]:
x = torch.eye(5, 5)
print(x)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])


**Create list of values​**

References: ​

https://pytorch.org/docs/stable/generated/torch.arange.html​

In [21]:
# create list of values atarting from 0 to 100 with step size of 20
x = torch.arange(start=0, end=100, step=20)
print(x)

tensor([ 0, 20, 40, 60, 80])


**Changing tensor types**

In [22]:
tensor = torch.tensor([-1, 0, 1, 2, 3])  # int64​
print(tensor.bool())  # [True, false, True, True, True]​
print(tensor.short())  # int16​
print(tensor.long())  # int64​
print(tensor.half())  # float16​
print(tensor.float())  # float32​
print(tensor.double())  # float64

tensor([ True, False,  True,  True,  True])
tensor([-1,  0,  1,  2,  3], dtype=torch.int16)
tensor([-1,  0,  1,  2,  3])
tensor([-1.,  0.,  1.,  2.,  3.], dtype=torch.float16)
tensor([-1.,  0.,  1.,  2.,  3.])
tensor([-1.,  0.,  1.,  2.,  3.], dtype=torch.float64)


**Convert between numpy and torch tensor​**

References:​

https://pytorch.org/docs/stable/generated/torch.from_numpy.html​

https://pytorch.org/docs/stable/generated/torch.Tensor.numpy.html

In [23]:
import numpy as np

numpy_array = np.random.rand(5, 5)
print(numpy_array)
torch_array = torch.from_numpy(numpy_array)
print(torch_array)
numpy_array_recon = torch_array.numpy()
print(numpy_array_recon)

[[0.14776683 0.6667     0.42254898 0.77647885 0.22955186]
 [0.48925051 0.35780103 0.31761522 0.56226993 0.64799746]
 [0.0969362  0.88294646 0.1325485  0.21415782 0.15728616]
 [0.66893868 0.86242267 0.71158171 0.81134987 0.2436438 ]
 [0.5398995  0.57759583 0.37733429 0.46963586 0.56987773]]
tensor([[0.1478, 0.6667, 0.4225, 0.7765, 0.2296],
        [0.4893, 0.3578, 0.3176, 0.5623, 0.6480],
        [0.0969, 0.8829, 0.1325, 0.2142, 0.1573],
        [0.6689, 0.8624, 0.7116, 0.8113, 0.2436],
        [0.5399, 0.5776, 0.3773, 0.4696, 0.5699]], dtype=torch.float64)
[[0.14776683 0.6667     0.42254898 0.77647885 0.22955186]
 [0.48925051 0.35780103 0.31761522 0.56226993 0.64799746]
 [0.0969362  0.88294646 0.1325485  0.21415782 0.15728616]
 [0.66893868 0.86242267 0.71158171 0.81134987 0.2436438 ]
 [0.5398995  0.57759583 0.37733429 0.46963586 0.56987773]]


**Addition**

**Method-1:**

References:

https://pytorch.org/docs/stable/generated/torch.sub.html

In [24]:
x = torch.tensor([1, 2, 3])
y = torch.tensor([4, 5, 6])

z = torch.empty(3)
torch.add(x, y, out=z)
print(z)

tensor([5., 7., 9.])


**Method-2:**

References:

https://pytorch.org/docs/stable/generated/torch.add.html

https://pytorch.org/docs/stable/generated/torch.Tensor.add_.html

In [25]:
x = torch.tensor([1, 2, 3])
y = torch.tensor([4, 5, 6])
z = torch.add(x, y)
print(z)

tensor([5, 7, 9])


**Method-3:**

reference:

https://pytorch.org/docs/stable/generated/torch.add.html

https://pytorch.org/docs/stable/generated/torch.Tensor.add_.html

In [26]:
x = torch.tensor([1, 2, 3])
y = torch.tensor([4, 5, 6])
z = x + y
print(z)

tensor([5, 7, 9])


**Inplace addition**

reference:

https://pytorch.org/docs/stable/generated/torch.add.html

https://pytorch.org/docs/stable/generated/torch.Tensor.add_.html

In [27]:
x = torch.tensor([1, 2, 3])
y = 2
x.add_(y)
print(x)

tensor([3, 4, 5])


**Subtraction​**

References:​

https://pytorch.org/docs/stable/generated/torch.sub.html​

https://pytorch.org/docs/stable/generated/torch.Tensor.sub_.html​

In [28]:
x = torch.tensor([1, 2, 3])
y = torch.tensor([4, 5, 6])
z = x - y
print(z)

tensor([-3, -3, -3])


**Inplace subtraction​**
​

References:​

https://pytorch.org/docs/stable/generated/torch.sub.html​

https://pytorch.org/docs/stable/generated/torch.Tensor.sub_.html​

In [29]:
x = torch.tensor([1, 2, 3])
y = 2
x.sub_(y)

tensor([-1,  0,  1])

**Element wise multiplication if both are tensor and of same shape​**

​
References:​

https://pytorch.org/docs/stable/generated/torch.mul.html​

In [30]:
x = torch.tensor([1, 2, 3])
y = torch.tensor([4, 5, 6])

z = torch.mul(x, y)  # can be written as z = x * y also​
print(z)

tensor([ 4, 10, 18])


**Scalar multiplication of elements from first array with integer provided as second element​**

References:​

https://pytorch.org/docs/stable/generated/torch.mul.html​

In [31]:
x = torch.tensor([1, 2, 3])
y = 2

z = torch.mul(x, y)  # can be written as z = x * y also
print(z)

tensor([2, 4, 6])


**Element wise division if both are tensor and of same shape​**

​
References:​

https://pytorch.org/docs/stable/generated/torch.div.html#torch.div

In [32]:
x = torch.tensor([1, 2, 3])
y = torch.tensor([4, 5, 6])

z = torch.div(x, y)  # can be written as z = x / y also​
print(z)

tensor([0.2500, 0.4000, 0.5000])


**Scalar division of elements from first array with integer provided as second element​**

References:​

https://pytorch.org/docs/stable/generated/torch.div.html#torch.div

In [33]:
x = torch.tensor([1, 2, 3])
y = 2

z = torch.div(x, y)  # can be written as z = x * y also
print(z)

tensor([0.5000, 1.0000, 1.5000])


**Element wise power of tensor:​** Takes the power of each element in input with exponent and returns a tensor with the result.

References:​

https://pytorch.org/docs/stable/generated/torch.pow.html

In [34]:
x = torch.tensor([1, 2, 3])
z = x.pow(2)
z = x**2
print(z)

tensor([1, 4, 9])


**Dot product:** Computes the dot product of two 1D tensors.

References:​

https://pytorch.org/docs/stable/generated/torch.dot.html

In [35]:
x = torch.tensor([2, 3])
y = torch.tensor([2, 1])
z = torch.dot(x, y)
print(z)

tensor(7)


**Matrix multiplication: ​** Matrix product of two tensors.

References:​

https://pytorch.org/docs/stable/generated/torch.matmul.html#torch.matmul​

In [36]:
x = torch.randn(2, 3)
y = torch.randn(3, 5)
z = torch.matmul(x, y)

print(x.shape)
print(y.shape)
print(z.shape)

torch.Size([2, 3])
torch.Size([3, 5])
torch.Size([2, 5])


**​Batch matrix multiplication​**

References:​

https://pytorch.org/docs/stable/generated/torch.matmul.html#torch.matmul​

In [37]:
x = torch.randn(10, 2, 3)
y = torch.randn(10, 3, 5)
z = torch.matmul(x, y)

print(x.shape)
print(y.shape)
print(z.shape)

torch.Size([10, 2, 3])
torch.Size([10, 3, 5])
torch.Size([10, 2, 5])


**Useful Mathematic operations​**

**Sum operation:​** Returns the sum of all elements in the input tensor.


References:​

https://pytorch.org/docs/stable/generated/torch.sum.html

In [38]:
x = torch.tensor([[1, 2, 3], [4, 5, 6]])
print(x)
print(x.shape)
z = torch.sum(x, dim=0)  # [5, 7, 9]​
print(z)
z = torch.sum(x, dim=1)  # [6, 15]​
print(z)
z = torch.sum(x, dim=(0, 1))  # 21​
print(z)

tensor([[1, 2, 3],
        [4, 5, 6]])
torch.Size([2, 3])
tensor([5, 7, 9])
tensor([ 6, 15])
tensor(21)


In [39]:
x = torch.ones(3, 4, 2)
x

tensor([[[1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.]]])

#### sum throguh axis = 0, in this case it means through channels

In [40]:
z = torch.sum(x, dim=0)
print(z)
print(z.shape)

tensor([[3., 3.],
        [3., 3.],
        [3., 3.],
        [3., 3.]])
torch.Size([4, 2])


**Mean operation:** Returns the mean value of all elements in the input tensor.

References:

https://pytorch.org/docs/stable/generated/torch.mean.html


In [41]:
x = torch.tensor([[1, 2, 3], [4, 5, 6]], dtype=torch.float32)
z = torch.mean(x, dim=0)  # through height
print(z)
z = torch.mean(x, dim=1)  # through width
print(z)
z = torch.mean(x, dim=(0, 1))  # through height and width
print(z)

tensor([2.5000, 3.5000, 4.5000])
tensor([2., 5.])
tensor(3.5000)


**Clamp operation**

Clamps all elements in input into the range [ min, max ].​​

References:​

https://pytorch.org/docs/stable/generated/torch.clamp.html​


In [42]:
min = -128
max = 365
x = (max - min) * torch.rand((2, 5)) + min
print(x.min(), x.max())
z = torch.clamp(x, min=0, max=255)
print(z.min(), z.max())

tensor(-68.7977) tensor(360.6734)
tensor(0.) tensor(255.)


**Indexing**

In [43]:
x = torch.rand((10, 64))
print(x[0].shape)
print(x[:, 0].shape)

x = torch.tensor([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
z = x[[2, 5, 8]]
print(z)
x = torch.tensor([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
z = x[(x < 3) | (x > 8)]
print(z)

torch.Size([64])
torch.Size([10])
tensor([3, 6, 9])
tensor([ 1,  2,  9, 10])


In [44]:
x = np.random.rand(10, 64)
print(x[0].shape)
print(x[:, 0].shape)

x = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
z = x[[2, 5, 8]]
print(z)
x = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
z = x[(x < 3) | (x > 8)]
print(z)

(64,)
(10,)
[3 6 9]
[ 1  2  9 10]


In [45]:
# x = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
# z = x[[2, 5, 8]]
# print(z)
# x = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
# z = x[(x<3) | (x>8)]
# print(z)

**Reshaping​:** Returns a new tensor with the same data as the self tensor but of a different shape.

References:​

https://pytorch.org/docs/stable/generated/torch.Tensor.view.html

In [46]:
x = torch.tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])
print(x.size())
z = x.view(3, 3)
print(z)
print(z.size())
z = x.view(3, -1)  # if other dimension is not known​
print(z.size())
print(z)

torch.Size([9])
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
torch.Size([3, 3])
torch.Size([3, 3])
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])


**Transpose​:** Performs tranpose of matrix

References:​

https://pytorch.org/docs/stable/generated/torch.t.html​


In [47]:
x = torch.rand(size=(3, 3))
print(x)
z = x.t()
print(z)

tensor([[0.0392, 0.8188, 0.2792],
        [0.6231, 0.4237, 0.0653],
        [0.1713, 0.5638, 0.1543]])
tensor([[0.0392, 0.6231, 0.1713],
        [0.8188, 0.4237, 0.5638],
        [0.2792, 0.0653, 0.1543]])


**Flatten:​** Flattens input by reshaping it into a one-dimensional tensor

References:

https://pytorch.org/docs/stable/generated/torch.flatten.html

In [48]:
x = torch.rand(size=(3, 3))
print(x)
z = torch.flatten(x)
print(z)

z = x.view(-1)
print(z)

tensor([[0.1668, 0.0044, 0.8219],
        [0.9732, 0.2644, 0.2318],
        [0.4089, 0.1373, 0.6784]])
tensor([0.1668, 0.0044, 0.8219, 0.9732, 0.2644, 0.2318, 0.4089, 0.1373, 0.6784])
tensor([0.1668, 0.0044, 0.8219, 0.9732, 0.2644, 0.2318, 0.4089, 0.1373, 0.6784])


**Concat operation​:** Concatenates the given sequence tensors in the given dimension. All tensors must either have the same shape (except in the concatenating dimension) or be empty.
​

References:​

https://pytorch.org/docs/stable/generated/torch.cat.html​

In [49]:
x = torch.rand(size=(10, 3, 128, 128))
y = torch.rand(size=(10, 3, 128, 128))
print(x.size())
print(y.size())

z = torch.cat([x, y], dim=0)
print(z.size())

z = torch.cat([x, y], dim=1)
print(z.size())

torch.Size([10, 3, 128, 128])
torch.Size([10, 3, 128, 128])
torch.Size([20, 3, 128, 128])
torch.Size([10, 6, 128, 128])


**Dimension switch:​** Returns a view of the original tensor input with its dimensions permuted.


References:​

https://pytorch.org/docs/stable/generated/torch.permute.html​

In [50]:
x = torch.rand(size=(10, 3, 128, 128))
print(x.shape)
z = x.permute(0, 2, 3, 1)
print(z.size())

torch.Size([10, 3, 128, 128])
torch.Size([10, 128, 128, 3])


**Adding or Removing extra dimension​:**

Squeeze: Returns a tensor with all the dimensions of input of size 1 removed.

Unsqueeze: Returns a new tensor with a dimension of size one inserted at the specified position.

References:​

https://pytorch.org/docs/stable/generated/torch.squeeze.html​

https://pytorch.org/docs/stable/generated/torch.unsqueeze.html​

In [51]:
x = torch.rand(size=(3, 128, 128))
print(x.size())
z = x.unsqueeze(0)
print(z.size())
y = z.squeeze(0)
print(y.size())

torch.Size([3, 128, 128])
torch.Size([1, 3, 128, 128])
torch.Size([3, 128, 128])
