# Pytorch Basics

#### Requirements
python​​3.x\
vscode or jupyter notebook

#### Create Virtual Environment
python3 -m venv venv3\
source venv3/bin/activate​
#### Visit pytorch website and get pytorch install command.​

Web: https://pytorch.org/get-started/locally/​

In [1]:
# verify pytorch installation
import torch

/home/skycam/aTYQI/vi/lib/python3.8/site-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [2]:
print(torch.__version__)

1.11.0+cu102


#### A tensor of : Height = 2,  Width = 3

In [3]:
tensor_a = torch.tensor([[1, 2, 3], [4, 5, 6]])  # Two rows, three columns
print(tensor_a)

tensor([[1, 2, 3],
        [4, 5, 6]])


In [4]:
tensor_a.shape

torch.Size([2, 3])

A tensor of : Chanel = 3, Height = 2, Width = 1

In [5]:
tensor_b = torch.tensor(
    [[[1], [4]], [[1], [4]], [[1], [4]]]
)  # Three channels, two rows, one column

In [6]:
tensor_b

tensor([[[1],
         [4]],

        [[1],
         [4]],

        [[1],
         [4]]])

Axis 0, 1, 2

In [7]:
tensor_b.shape

torch.Size([3, 2, 1])

**We can also specify data type while creating tensor**

References: https://pytorch.org/docs/stable/tensors.html#data-types

In [8]:
tensor_a = torch.tensor(
    [[1, 2, 3], [4, 5, 6]], dtype=torch.float16
)  # two rows and three columns tensor with float16 values
print(tensor_a)

tensor([[1., 2., 3.],
        [4., 5., 6.]], dtype=torch.float16)


**We can also specify device type while creating tensor**

References: https://pytorch.org/docs/stable/tensor_attributes.html#torch-device

In [9]:
print(torch.cuda.is_available())

False


/home/skycam/aTYQI/vi/lib/python3.8/site-packages/torch/cuda/__init__.py:82: UserWarning: CUDA initialization: CUDA unknown error - this may be due to an incorrectly set up environment, e.g. changing env variable CUDA_VISIBLE_DEVICES after program start. Setting the available devices to be zero. (Triggered internally at  ../c10/cuda/CUDAFunctions.cpp:112.)
  return torch._C._cuda_getDeviceCount() > 0


In [10]:
## usual practise is that we decide device in start

device = "cuda" if torch.cuda.is_available() else "cpu"
tensor_c = torch.tensor(
    [[1, 2, 3], [4, 5, 6]], dtype=torch.float32, device=device
)  # two rows and three columns tensor with float32 values on specified device

In [11]:
tensor_c

tensor([[1., 2., 3.],
        [4., 5., 6.]])

**Move tensor across devices**

In [12]:
device = "cuda" if torch.cuda.is_available() else "cpu"

In [13]:
tensor_a = torch.tensor([[1, 2, 3], [4, 5, 6]])
tensor_a = tensor_a.to(device)

#### Common Initialization methods:​

​
**Uninitialized data:**

reference: ​

https://pytorch.org/docs/stable/generated/torch.empty.html​

In [14]:
x = torch.empty(size=(10, 10))
print(x)

tensor([[ 3.2317e-37,  0.0000e+00,  9.4691e-36,  0.0000e+00,  8.9683e-44,
          0.0000e+00,  1.1210e-43,  0.0000e+00,  9.4690e-36,  0.0000e+00],
        [        nan,  9.5936e-35, -2.2198e+38, -1.7811e+38,  1.9753e-33,
          5.0273e-31, -1.8210e+38, -1.9407e+38, -1.1302e+11, -1.4705e+21],
        [ 4.7090e-33,  4.5619e-41,  4.6331e-33,  4.5619e-41, -3.0519e+10,
          1.3975e-36,  2.4803e-43,  0.0000e+00,  9.4496e-36,  0.0000e+00],
        [ 1.0721e-32,  4.5619e-41,  4.6100e-33,  4.5619e-41,  1.3297e-38,
          0.0000e+00,  3.4238e+06, -1.0920e+35,  4.6100e-33,  4.5619e-41],
        [ 1.3297e-38,  0.0000e+00,  1.4338e+27, -3.6470e+35,  4.6101e-33,
          4.5619e-41,  1.3593e-43,  0.0000e+00,  1.3156e-37,  0.0000e+00],
        [ 9.4690e-36,  0.0000e+00,  4.6283e-33,  4.5619e-41,  5.7764e-13,
          4.3304e-16,  4.6620e-33,  4.5619e-41,  4.6283e-33,  4.5619e-41],
        [ 2.0258e-33,  8.2083e-13,  4.6243e-44,  0.0000e+00,  9.4269e-36,
          0.0000e+00,  9.4691e-3

**All zero data**

reference:
https://pytorch.org/docs/stable/generated/torch.zeros.html

In [15]:
x = torch.zeros(size=(10, 10))
print(x)

tensor([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])


**All ones data**​

reference: ​
https://pytorch.org/docs/stable/generated/torch.ones.html​​

In [16]:
x = torch.ones(size=(10, 10))
print(x)

tensor([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])


**All random numbers with uniform distribution between interval [0, 1)​**​​
​

References: ​

https://pytorch.org/docs/stable/generated/torch.rand.html​

​

In [17]:
x = torch.rand(size=(5, 5))
print(x)

tensor([[0.1418, 0.2798, 0.7604, 0.8670, 0.0790],
        [0.1945, 0.0984, 0.6205, 0.2159, 0.5595],
        [0.8810, 0.2585, 0.8827, 0.8285, 0.9515],
        [0.9800, 0.2429, 0.1013, 0.8576, 0.9671],
        [0.1108, 0.8865, 0.1154, 0.1142, 0.2389]])


**All random numbers with uniform distribution between with given mean and std dev​**

<b>NOTE: "_" after normal means that it is an inplace operation​</b>

References: ​

https://pytorch.org/docs/stable/generated/torch.rand.html​

In [18]:
x = torch.empty(size=(5, 5)).normal_(mean=0, std=2)
print(x)

tensor([[-0.4317, -0.1443, -0.3429,  0.4909, -3.4533],
        [-0.9703, -1.7018,  2.2065,  5.7212,  0.5072],
        [-0.1565, -0.9897,  2.0426,  0.9227, -1.1667],
        [-1.0137, -0.1164,  2.6197, -3.5958, -1.2723],
        [-0.1951, -1.9773,  1.9311, -1.6501, -0.4094]])


**Create evenly spaced values between given range​**

References:​

https://pytorch.org/docs/stable/generated/torch.linspace.html

In [19]:
# create list of 13 numbers between 1 to 54 which are evenly spaced
x = torch.linspace(start=1, end=54, steps=13)
print(x)

tensor([ 1.0000,  5.4167,  9.8333, 14.2500, 18.6667, 23.0833, 27.5000, 31.9167,
        36.3333, 40.7500, 45.1667, 49.5833, 54.0000])


**Identity matrix**​

reference: ​

https://pytorch.org/docs/stable/generated/torch.eye.html​

In [20]:
x = torch.eye(5, 5)
print(x)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])


**Create list of values​**

References: ​

https://pytorch.org/docs/stable/generated/torch.arange.html​

In [21]:
# create list of values atarting from 0 to 100 with step size of 20
x = torch.arange(start=0, end=100, step=20)
print(x)

tensor([ 0, 20, 40, 60, 80])


**Changing tensor types**

In [22]:
tensor = torch.tensor([-1, 0, 1, 2, 3])  # int64​
print(tensor.bool())  # [True, false, True, True, True]​
print(tensor.short())  # int16​
print(tensor.long())  # int64​
print(tensor.half())  # float16​
print(tensor.float())  # float32​
print(tensor.double())  # float64

tensor([ True, False,  True,  True,  True])
tensor([-1,  0,  1,  2,  3], dtype=torch.int16)
tensor([-1,  0,  1,  2,  3])
tensor([-1.,  0.,  1.,  2.,  3.], dtype=torch.float16)
tensor([-1.,  0.,  1.,  2.,  3.])
tensor([-1.,  0.,  1.,  2.,  3.], dtype=torch.float64)


**Convert between numpy and torch tensor​**

References:​

https://pytorch.org/docs/stable/generated/torch.from_numpy.html​

https://pytorch.org/docs/stable/generated/torch.Tensor.numpy.html

In [23]:
import numpy as np

numpy_array = np.random.rand(5, 5)
print(numpy_array)
torch_array = torch.from_numpy(numpy_array)
print(torch_array)
numpy_array_recon = torch_array.numpy()
print(numpy_array_recon)

[[0.88536034 0.20845905 0.8410834  0.98067797 0.5431732 ]
 [0.63409764 0.24062979 0.11939822 0.59020316 0.36167987]
 [0.95982442 0.104679   0.72931589 0.18962074 0.61085778]
 [0.18807456 0.99013049 0.3865906  0.60681579 0.94593867]
 [0.53689106 0.45801062 0.27143292 0.02986875 0.63770315]]
tensor([[0.8854, 0.2085, 0.8411, 0.9807, 0.5432],
        [0.6341, 0.2406, 0.1194, 0.5902, 0.3617],
        [0.9598, 0.1047, 0.7293, 0.1896, 0.6109],
        [0.1881, 0.9901, 0.3866, 0.6068, 0.9459],
        [0.5369, 0.4580, 0.2714, 0.0299, 0.6377]], dtype=torch.float64)
[[0.88536034 0.20845905 0.8410834  0.98067797 0.5431732 ]
 [0.63409764 0.24062979 0.11939822 0.59020316 0.36167987]
 [0.95982442 0.104679   0.72931589 0.18962074 0.61085778]
 [0.18807456 0.99013049 0.3865906  0.60681579 0.94593867]
 [0.53689106 0.45801062 0.27143292 0.02986875 0.63770315]]


**Addition**

**Method-1:**

References:

https://pytorch.org/docs/stable/generated/torch.sub.html

In [24]:
x = torch.tensor([1, 2, 3])
y = torch.tensor([4, 5, 6])

z = torch.empty(3)
torch.add(x, y, out=z)
print(z)

tensor([5., 7., 9.])


**Method-2:**

References:

https://pytorch.org/docs/stable/generated/torch.add.html

https://pytorch.org/docs/stable/generated/torch.Tensor.add_.html

In [25]:
x = torch.tensor([1, 2, 3])
y = torch.tensor([4, 5, 6])
z = torch.add(x, y)
print(z)

tensor([5, 7, 9])


**Method-3:**

reference:

https://pytorch.org/docs/stable/generated/torch.add.html

https://pytorch.org/docs/stable/generated/torch.Tensor.add_.html

In [26]:
x = torch.tensor([1, 2, 3])
y = torch.tensor([4, 5, 6])
z = x + y
print(z)

tensor([5, 7, 9])


**Inplace addition**

reference:

https://pytorch.org/docs/stable/generated/torch.add.html

https://pytorch.org/docs/stable/generated/torch.Tensor.add_.html

In [27]:
x = torch.tensor([1, 2, 3])
y = 2
x.add_(y)
print(x)

tensor([3, 4, 5])


**Subtraction​**

References:​

https://pytorch.org/docs/stable/generated/torch.sub.html​

https://pytorch.org/docs/stable/generated/torch.Tensor.sub_.html​

In [28]:
x = torch.tensor([1, 2, 3])
y = torch.tensor([4, 5, 6])
z = x - y
print(z)

tensor([-3, -3, -3])


**Inplace subtraction​**
​

References:​

https://pytorch.org/docs/stable/generated/torch.sub.html​

https://pytorch.org/docs/stable/generated/torch.Tensor.sub_.html​

In [29]:
x = torch.tensor([1, 2, 3])
y = 2
x.sub_(y)

tensor([-1,  0,  1])

**Element wise multiplication if both are tensor and of same shape​**

​
References:​

https://pytorch.org/docs/stable/generated/torch.mul.html​

In [30]:
x = torch.tensor([1, 2, 3])
y = torch.tensor([4, 5, 6])

z = torch.mul(x, y)  # can be written as z = x * y also​
print(z)

tensor([ 4, 10, 18])


**Scalar multiplication of elements from first array with integer provided as second element​**

References:​

https://pytorch.org/docs/stable/generated/torch.mul.html​

In [31]:
x = torch.tensor([1, 2, 3])
y = 2

z = torch.mul(x, y)  # can be written as z = x * y also
print(z)

tensor([2, 4, 6])


**Element wise division if both are tensor and of same shape​**

​
References:​

https://pytorch.org/docs/stable/generated/torch.div.html#torch.div

In [32]:
x = torch.tensor([1, 2, 3])
y = torch.tensor([4, 5, 6])

z = torch.div(x, y)  # can be written as z = x / y also​
print(z)

tensor([0.2500, 0.4000, 0.5000])


**Scalar division of elements from first array with integer provided as second element​**

References:​

https://pytorch.org/docs/stable/generated/torch.div.html#torch.div

In [33]:
x = torch.tensor([1, 2, 3])
y = 2

z = torch.div(x, y)  # can be written as z = x * y also
print(z)

tensor([0.5000, 1.0000, 1.5000])


**Element wise power of tensor:​** Takes the power of each element in input with exponent and returns a tensor with the result.

References:​

https://pytorch.org/docs/stable/generated/torch.pow.html

In [34]:
x = torch.tensor([1, 2, 3])
z = x.pow(2)
z = x**2
print(z)

tensor([1, 4, 9])


**Dot product:** Computes the dot product of two 1D tensors.

References:​

https://pytorch.org/docs/stable/generated/torch.dot.html

In [35]:
x = torch.tensor([2, 3])
y = torch.tensor([2, 1])
z = torch.dot(x, y)
print(z)

tensor(7)


**Matrix multiplication: ​** Matrix product of two tensors.

References:​

https://pytorch.org/docs/stable/generated/torch.matmul.html#torch.matmul​

In [36]:
x = torch.randn(2, 3)
y = torch.randn(3, 5)
z = torch.matmul(x, y)

print(x.shape)
print(y.shape)
print(z.shape)

torch.Size([2, 3])
torch.Size([3, 5])
torch.Size([2, 5])


**​Batch matrix multiplication​**

References:​

https://pytorch.org/docs/stable/generated/torch.matmul.html#torch.matmul​

In [37]:
x = torch.randn(10, 2, 3)
y = torch.randn(10, 3, 5)
z = torch.matmul(x, y)

print(x.shape)
print(y.shape)
print(z.shape)

torch.Size([10, 2, 3])
torch.Size([10, 3, 5])
torch.Size([10, 2, 5])


**Useful Mathematic operations​**

**Sum operation:​** Returns the sum of all elements in the input tensor.


References:​

https://pytorch.org/docs/stable/generated/torch.sum.html

In [38]:
x = torch.tensor([[1, 2, 3], [4, 5, 6]])
print(x)
print(x.shape)
z = torch.sum(x, dim=0)  # [5, 7, 9]​
print(z)
z = torch.sum(x, dim=1)  # [6, 15]​
print(z)
z = torch.sum(x, dim=(0, 1))  # 21​
print(z)

tensor([[1, 2, 3],
        [4, 5, 6]])
torch.Size([2, 3])
tensor([5, 7, 9])
tensor([ 6, 15])
tensor(21)


In [39]:
x = torch.ones(3, 4, 2)
x

tensor([[[1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.]]])

#### sum throguh axis = 0, in this case it means through channels

In [40]:
z = torch.sum(x, dim=0)
print(z)
print(z.shape)

tensor([[3., 3.],
        [3., 3.],
        [3., 3.],
        [3., 3.]])
torch.Size([4, 2])


**Mean operation:** Returns the mean value of all elements in the input tensor.

References:

https://pytorch.org/docs/stable/generated/torch.mean.html


In [41]:
x = torch.tensor([[1, 2, 3], [4, 5, 6]], dtype=torch.float32)
z = torch.mean(x, dim=0)  # through height
print(z)
z = torch.mean(x, dim=1)  # through width
print(z)
z = torch.mean(x, dim=(0, 1))  # through height and width
print(z)

tensor([2.5000, 3.5000, 4.5000])
tensor([2., 5.])
tensor(3.5000)


**Clamp operation**

Clamps all elements in input into the range [ min, max ].​​

References:​

https://pytorch.org/docs/stable/generated/torch.clamp.html​


In [42]:
min = -128
max = 365
x = (max - min) * torch.rand((2, 5)) + min
print(x.min(), x.max())
z = torch.clamp(x, min=0, max=255)
print(z.min(), z.max())

tensor(-127.2054) tensor(355.8472)
tensor(0.) tensor(255.)


**Indexing**

In [43]:
x = torch.rand((10, 64))
print(x[0].shape)
print(x[:, 0].shape)

x = torch.tensor([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
z = x[[2, 5, 8]]
print(z)
x = torch.tensor([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
z = x[(x < 3) | (x > 8)]
print(z)

torch.Size([64])
torch.Size([10])
tensor([3, 6, 9])
tensor([ 1,  2,  9, 10])


In [44]:
x = np.random.rand(10, 64)
print(x[0].shape)
print(x[:, 0].shape)

x = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
z = x[[2, 5, 8]]
print(z)
x = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
z = x[(x < 3) | (x > 8)]
print(z)

(64,)
(10,)
[3 6 9]
[ 1  2  9 10]


In [45]:
# x = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
# z = x[[2, 5, 8]]
# print(z)
# x = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
# z = x[(x<3) | (x>8)]
# print(z)

**Reshaping​:** Returns a new tensor with the same data as the self tensor but of a different shape.

References:​

https://pytorch.org/docs/stable/generated/torch.Tensor.view.html

In [46]:
x = torch.tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])
print(x.size())
z = x.view(3, 3)
print(z)
print(z.size())
z = x.view(3, -1)  # if other dimension is not known​
print(z.size())
print(z)

torch.Size([9])
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
torch.Size([3, 3])
torch.Size([3, 3])
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])


**Transpose​:** Performs tranpose of matrix

References:​

https://pytorch.org/docs/stable/generated/torch.t.html​


In [47]:
x = torch.rand(size=(3, 3))
print(x)
z = x.t()
print(z)

tensor([[0.3453, 0.1829, 0.0977],
        [0.8530, 0.2664, 0.9835],
        [0.5066, 0.3739, 0.2430]])
tensor([[0.3453, 0.8530, 0.5066],
        [0.1829, 0.2664, 0.3739],
        [0.0977, 0.9835, 0.2430]])


**Flatten:​** Flattens input by reshaping it into a one-dimensional tensor

References:

https://pytorch.org/docs/stable/generated/torch.flatten.html

In [48]:
x = torch.rand(size=(3, 3))
print(x)
z = torch.flatten(x)
print(z)

z = x.view(-1)
print(z)

tensor([[0.9245, 0.3522, 0.6519],
        [0.5641, 0.6606, 0.4910],
        [0.9999, 0.1200, 0.2491]])
tensor([0.9245, 0.3522, 0.6519, 0.5641, 0.6606, 0.4910, 0.9999, 0.1200, 0.2491])
tensor([0.9245, 0.3522, 0.6519, 0.5641, 0.6606, 0.4910, 0.9999, 0.1200, 0.2491])


**Concat operation​:** Concatenates the given sequence tensors in the given dimension. All tensors must either have the same shape (except in the concatenating dimension) or be empty.
​

References:​

https://pytorch.org/docs/stable/generated/torch.cat.html​

In [49]:
x = torch.rand(size=(10, 3, 128, 128))
y = torch.rand(size=(10, 3, 128, 128))
print(x.size())
print(y.size())

z = torch.cat([x, y], dim=0)
print(z.size())

z = torch.cat([x, y], dim=1)
print(z.size())

torch.Size([10, 3, 128, 128])
torch.Size([10, 3, 128, 128])
torch.Size([20, 3, 128, 128])
torch.Size([10, 6, 128, 128])


**Dimension switch:​** Returns a view of the original tensor input with its dimensions permuted.


References:​

https://pytorch.org/docs/stable/generated/torch.permute.html​

In [50]:
x = torch.rand(size=(10, 3, 128, 128))
print(x.shape)
z = x.permute(0, 2, 3, 1)
print(z.size())

torch.Size([10, 3, 128, 128])
torch.Size([10, 128, 128, 3])


**Adding or Removing extra dimension​:**

Squeeze: Returns a tensor with all the dimensions of input of size 1 removed.

Unsqueeze: Returns a new tensor with a dimension of size one inserted at the specified position.

References:​

https://pytorch.org/docs/stable/generated/torch.squeeze.html​

https://pytorch.org/docs/stable/generated/torch.unsqueeze.html​

In [51]:
x = torch.rand(size=(3, 128, 128))
print(x.size())
z = x.unsqueeze(0)
print(z.size())
y = z.squeeze(0)
print(y.size())

torch.Size([3, 128, 128])
torch.Size([1, 3, 128, 128])
torch.Size([3, 128, 128])
