## Requirements:​
python​​

#### Step-1: Visit following website, Select the preferences and run the install command.​

Web: https://pytorch.org/get-started/locally/​

Optional: create seperate virtual environment for installation of pytorch​

    python3 -m venv pytorch​
    source pytorch/bin/activate​


#### Step-2: Verify installation with following sequence of commands in terminal.​

python <br>
\>>> import torch <br>
\>>> print(torch.\__version\__)

In [1]:
# verify pytorch installation
import torch
print(torch.__version__)

1.13.1+cpu


In [2]:
tensor_a = torch.tensor([[1, 2, 3], [4, 5, 6]]) # two rows and three columns tensor​
print(tensor_a)

tensor([[1, 2, 3],
        [4, 5, 6]])


**We can also specify data type while creating tensor**

References: https://pytorch.org/docs/stable/tensors.html#data-types

In [3]:
tensor_a = torch.tensor([[1, 2, 3], [4, 5, 6]], dtype=torch.float16) # two rows and three columns tensor with float16 values
print(tensor_a)

tensor([[1., 2., 3.],
        [4., 5., 6.]], dtype=torch.float16)


**We can also specify device type while creating tensor**

References: https://pytorch.org/docs/stable/tensor_attributes.html#torch-device

In [4]:
tensor_a = torch.tensor([[1, 2, 3], [4, 5, 6]], dtype=torch.float32, device="cpu") # two rows and three columns tensor with float32 values on specified device

## using cuda instead

# tensor_a = torch.tensor([[1, 2, 3], [4, 5, 6]], dtype=torch.float32, device="cuda:0") # two rows and three columns tensor with float32 values on specified device

## how to check if torch is cuda enabled

print(torch.cuda.is_available())

## usual practise is that we decide device in start

device = "cuda:0" if torch.cuda.is_available() else "cpu"
tensor_a = torch.tensor([[1, 2, 3], [4, 5, 6]], dtype=torch.float32, device=device) # two rows and three columns tensor with float32 values on specified device
print(tensor_a)

False
tensor([[1., 2., 3.],
        [4., 5., 6.]])


#### Common Initialization methods:​

​
**Uninitialized data:**

reference: ​

https://pytorch.org/docs/stable/generated/torch.empty.html​

In [5]:
x = torch.empty(size=(10, 10))
print(x)

tensor([[-4.5998e+35,  4.5688e-41, -4.5998e+35,  4.5688e-41,  4.4842e-44,
          0.0000e+00,  1.5695e-43,  0.0000e+00,  5.0306e-36,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,
          0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  9.1084e-44,  0.0000e+00,  5.0257e-36,
          0.0000e+00,  5.0246e-36,  0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 4.6243e-44,  0.0000e+00,  5.0248e-36,  0.0000e+00,  5.3950e-43,
          0.0000e+00,  5.0277e-36,  0.0000e+00,  5.0242e-36,  0.0000e+00],
        [ 1.4013e-45,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,
          0.0000e+00,  4.6243e-44,  0.0000e+00,  5.0277e-36,  0.0000e+00],
        [ 5.0248e-36,  0.0000e+00,  1.1210e-43,  0.0000e+00,  8.9683e-44,
          0.0000e+00,  5.0307e-36,  0.0000e+00,  2.4803e-43,  0.0000e+00],
        [ 5.0257e-36,  0.0000e+00, -4.5996e+35,  4.5688e-41,  0.0000e+00,
          0.0000e+00,  0.0000e+0

**All zero data**

reference:
https://pytorch.org/docs/stable/generated/torch.zeros.html

In [6]:
x = torch.zeros(size=(10, 10))
print(x)

tensor([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])


**All ones data: **​

reference: ​
https://pytorch.org/docs/stable/generated/torch.ones.html​​

In [ ]:
x = torch.ones(size=(10, 10))
print(x)

**All random numbers with uniform distribution between interval [0, 1)​**​​
​

References: ​

https://pytorch.org/docs/stable/generated/torch.rand.html​

​

In [ ]:
x = torch.rand(size=(5, 5))
print(x)

**All random numbers with uniform distribution between with given mean and std dev​**

<b>NOTE: "_" after normal means that it is an inplace operation​</b>

References: ​

https://pytorch.org/docs/stable/generated/torch.rand.html​

In [ ]:
x = torch.empty(size=(5, 5)).normal_(mean=0, std=2)
print(x)

**Create evenly spaced valus betwene given range​**

References:​

https://pytorch.org/docs/stable/generated/torch.linspace.html

In [ ]:
# create list of 13 numbers between 1 to 54 which are evenly spaced
x = torch.linspace(start=1, end=54, steps=13)
print(x)

**Identity matrix**​

reference: ​

https://pytorch.org/docs/stable/generated/torch.eye.html​

In [ ]:
x = torch.eye(5, 5)
print(x)

**Create list of values​**

References: ​

https://pytorch.org/docs/stable/generated/torch.arange.html​

In [ ]:
# create list of values atarting from 0 to 100 with step size of 20
x = torch.arange(start=0, end=100, step=20)
print(x)

**Changing tensor types**

In [ ]:
tensor = torch.tensor([-1, 0, 1, 2, 3]) # int64​
print(tensor.bool()) # [True, false, True, True, True]​
print(tensor.short()) # int16​
print(tensor.long()) # int64​
print(tensor.half()) # float16​
print(tensor.float()) # float32​
print(tensor.double()) # float64

**Convert between numpy and torch tensor​**

References:​

https://pytorch.org/docs/stable/generated/torch.from_numpy.html​

https://pytorch.org/docs/stable/generated/torch.Tensor.numpy.html

In [ ]:
import numpy as np
numpy_array = np.random.rand(5, 5)
print(numpy_array)
torch_array = torch.from_numpy(numpy_array)
print(torch_array)
numpy_array_recon = torch_array.numpy()
print(numpy_array_recon)

**Addition**

**Method-1:**

reference:

https://pytorch.org/docs/stable/generated/torch.sub.html

In [ ]:
x = torch.tensor([1, 2, 3])
y = torch.tensor([4, 5, 6])

z = torch.empty(3)
torch.add(x, y, out=z)
print(z)

**Method-2:**

reference:

https://pytorch.org/docs/stable/generated/torch.add.html

https://pytorch.org/docs/stable/generated/torch.Tensor.add_.html

In [ ]:
x = torch.tensor([1, 2, 3])
y = torch.tensor([4, 5, 6])
z = torch.add(x, y)
print(z)

**Method-3:**

reference:

https://pytorch.org/docs/stable/generated/torch.add.html

https://pytorch.org/docs/stable/generated/torch.Tensor.add_.html

In [ ]:
x = torch.tensor([1, 2, 3])
y = torch.tensor([4, 5, 6])
z = x + y
print(z)

**Inplace addition**

reference:

https://pytorch.org/docs/stable/generated/torch.add.html

https://pytorch.org/docs/stable/generated/torch.Tensor.add_.html

In [ ]:
x = torch.tensor([1, 2, 3])
y = 2
x.add_(y)
print(x)

**Subtraction​**

​

References:​

https://pytorch.org/docs/stable/generated/torch.sub.html​

https://pytorch.org/docs/stable/generated/torch.Tensor.sub_.html​

In [ ]:
x = torch.tensor([1, 2, 3])
y = torch.tensor([4, 5, 6])
z = x - y
print(z)

**Inplace subtraction​**
​

References:​

https://pytorch.org/docs/stable/generated/torch.sub.html​

https://pytorch.org/docs/stable/generated/torch.Tensor.sub_.html​

In [ ]:
x = torch.tensor([1, 2, 3])
y = 2
x.sub_(y)

**Element wise multiplication if both are tensor and of same shape​**
​
References:​

https://pytorch.org/docs/stable/generated/torch.mul.html​

In [ ]:
x = torch.tensor([1, 2, 3])
y = torch.tensor([4, 5, 6])

z = torch.mul(x, y) # can be written as z = x * y also​
print(z)

**Scalar multiplication of elements from first array with integer provided as second element​**

References:​

https://pytorch.org/docs/stable/generated/torch.mul.html​

In [ ]:
x = torch.tensor([1, 2, 3])
y = 2

z = torch.mul(x, y) # can be written as z = x * y also
print(z)

**Element wise division if both are tensor and of same shape​**
​
References:​

https://pytorch.org/docs/stable/generated/torch.div.html#torch.div

In [ ]:
x = torch.tensor([1, 2, 3])
y = torch.tensor([4, 5, 6])

z = torch.div(x, y) # can be written as z = x / y also​
print(z)

**Scalar division of elements from first array with integer provided as second element​**

References:​

https://pytorch.org/docs/stable/generated/torch.div.html#torch.div

In [ ]:
x = torch.tensor([1, 2, 3])
y = 2

z = torch.div(x, y) # can be written as z = x * y also
print(z)

**Element wise power of tensor:​** Takes the power of each element in input with exponent and returns a tensor with the result.

References:​

https://pytorch.org/docs/stable/generated/torch.pow.html

In [ ]:
x = torch.tensor([1, 2, 3])
z = x.pow(2)
z = x**2
print(z)

**Dot product:** Computes the dot product of two 1D tensors.

References:​

https://pytorch.org/docs/stable/generated/torch.dot.html

In [ ]:
x = torch.tensor([2, 3])
y = torch.tensor([2, 1])
z = torch.dot(x, y)
print(z)

**Matrix multiplication: ​** Matrix product of two tensors.

References:​

https://pytorch.org/docs/stable/generated/torch.matmul.html#torch.matmul​

In [ ]:
x = torch.randn(2, 3)
y = torch.randn(3, 5)
z = torch.matmul(x, y)

print(x.shape)
print(y.shape)
print(z.shape)

**​Batch matrix multiplication​**

References:​

https://pytorch.org/docs/stable/generated/torch.matmul.html#torch.matmul​

In [ ]:
x = torch.randn(10, 2, 3)
y = torch.randn(10, 3, 5)
z = torch.matmul(x, y)

print(x.shape)
print(y.shape)
print(z.shape)

**Useful Mathematic operations​**

**Sum operation:​** Returns the sum of all elements in the input tensor.


References:​

https://pytorch.org/docs/stable/generated/torch.sum.html

In [ ]:
x = torch.tensor([[1, 2, 3], [4, 5, 6]])
z = torch.sum(x, dim=0) # [5, 7, 9]​
print(z)
z = torch.sum(x, dim=1) # [6, 15]​
print(z)
z = torch.sum(x, dim=(0,1)) # 21​
print(z)

**Mean operation:** Returns the mean value of all elements in the input tensor.

References:

https://pytorch.org/docs/stable/generated/torch.mean.html


In [ ]:
x = torch.tensor([[1, 2, 3], [4, 5, 6]], dtype=torch.float32)
z = torch.mean(x, dim=0) # [2.5000, 3.5000, 4.5000]​
print(z)
z = torch.mean(x, dim=1) # [2., 5.]​
print(z)
z = torch.mean(x, dim=(0,1)) # 3.5​
print(z)

**Clamp operation**

Clamps all elements in input into the range [ min, max ].​​

References:​

https://pytorch.org/docs/stable/generated/torch.clamp.html​


In [ ]:
min = -128
max = 365
x = (max-min)*torch.rand((2, 5)) + min
print(x.min(), x.max())
z = torch.clamp(x, min=0, max=255)
print(z.min(), z.max())

**Indexing**

In [ ]:
x = torch.rand((10, 64))
print(x[0].shape)
print(x[:, 0].shape)

x = torch.tensor([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
z = x[[2, 5, 8]]
print(z)
x = torch.tensor([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
z = x[(x<3) | (x>8)]
print(z)

In [ ]:
x = np.random.rand(10, 64)
print(x[0].shape)
print(x[:, 0].shape)

x = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
z = x[[2, 5, 8]]
print(z)
x = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
z = x[(x<3) | (x>8)]
print(z)

In [ ]:
# x = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
# z = x[[2, 5, 8]]
# print(z)
# x = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
# z = x[(x<3) | (x>8)]
# print(z)

**Reshaping​:** Returns a new tensor with the same data as the self tensor but of a different shape.

References:​

https://pytorch.org/docs/stable/generated/torch.Tensor.view.html

In [ ]:
x = torch.tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])
print(x.size())
z = x.view(3, 3)
print(z)
print(z.size())
z = x.view(3, -1) # if other dimension is not known​
print(z.size())
print(z)

**Transpose​:** Performs tranpose of matrix

References:​

https://pytorch.org/docs/stable/generated/torch.t.html​


In [ ]:
x = torch.rand(size=(3,3))
print(x)
z = x.t()
print(z)

**Flatten:​** Flattens input by reshaping it into a one-dimensional tensor

References:

https://pytorch.org/docs/stable/generated/torch.flatten.html

In [ ]:
x = torch.rand(size=(3,3))
print(x)
z = torch.flatten(x)
print(z)

z = x.view(-1)
print(z)

**Concat operation​:** Concatenates the given sequence tensors in the given dimension. All tensors must either have the same shape (except in the concatenating dimension) or be empty.
​

References:​

https://pytorch.org/docs/stable/generated/torch.cat.html​

In [ ]:
x = torch.rand(size=(10, 3, 128, 128))
y = torch.rand(size=(10, 3, 128, 128))
print(x.size())
print(y.size())

z = torch.cat([x, y], dim=0)
print(z.size())

z = torch.cat([x, y], dim=1)
print(z.size())

**Dimension switch:​** Returns a view of the original tensor input with its dimensions permuted.


References:​

https://pytorch.org/docs/stable/generated/torch.permute.html​

In [ ]:
x = torch.rand(size=(10, 3, 128, 128))
print(x.shape)
z = x.permute(0, 2, 3, 1)
print(z.size())

**Adding or Removing extra dimension​:**

Squeeze: Returns a tensor with all the dimensions of input of size 1 removed.
Unsqueeze: Returns a new tensor with a dimension of size one inserted at the specified position.

References:​

https://pytorch.org/docs/stable/generated/torch.squeeze.html​

https://pytorch.org/docs/stable/generated/torch.unsqueeze.html​

In [ ]:
x = torch.rand(size=(3, 128, 128))
print(x.size())
z = x.unsqueeze(0)
print(z.size())
y = z.squeeze(0)
print(y.size())