## Sovling LINE problem with a single perceptron

In [10]:
# imports

import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

device = 'cuda' if torch.cuda.is_available() else 'cpu'

In [12]:
X = torch.FloatTensor([[0], [1], [2], [3], [4], [5], [6], [7], [8], [9], [10], [11]]).to(device)
Y = torch.FloatTensor([[5], [8], [11], [14], [17], [20], [23], [26], [29], [32], [35], [38]]).to(device) # 3x+5

nn.Linear = Applies a linear transformation to the incoming data: Y = w*X^T+b

nn.Sigmoid: Applies the element-wise sigmoid function

<img src="https://pytorch.org/docs/stable/_images/Sigmoid.png">

References:

https://pytorch.org/docs/stable/generated/torch.nn.Linear.html

https://pytorch.org/docs/stable/generated/torch.nn.Sigmoid.html

In [13]:
# Perceptron model
model = nn.Sequential(
            nn.Linear(1, 1, bias=True),
        ).to(device)

In [14]:
print("Starting weights: {}".format(model[0].weight))
print("Starting bias: {}".format(model[0].bias))

Starting weights: Parameter containing:
tensor([[-0.7049]], requires_grad=True)
Starting bias: Parameter containing:
tensor([0.4947], requires_grad=True)


#### [TODO] loss and optimizer significance


In [5]:
criterion = nn.MSELoss()
optimizer = optim.SGD(model.parameters(), lr=0.01)

In [6]:
for step in range(5000):
    pred = model(X)
    loss = criterion(pred, Y)
    
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()
    
    if step % 1000==0:
        print('step:', step, " loss:", loss.item())

step: 0  loss: 307.0710754394531
step: 1000  loss: 7.259591075126082e-05
step: 2000  loss: 1.107101410546818e-09
step: 3000  loss: 5.492021837305572e-10
step: 4000  loss: 5.492021837305572e-10


In [7]:
pred = model(X)
print(pred)

tensor([[ 5.0000],
        [ 8.0000],
        [11.0000],
        [14.0000],
        [17.0000],
        [20.0000],
        [23.0000],
        [26.0000],
        [29.0000],
        [32.0000],
        [35.0000],
        [38.0000]], grad_fn=<AddmmBackward0>)


In [8]:
new_value = torch.FloatTensor([[12]]).to(device)
new_pred = model(new_value)
print(new_pred)

tensor([[41.0000]], grad_fn=<AddmmBackward0>)


In [9]:
print("Learned weights: {}".format(model[0].weight.flatten()))
print("Learned bias: {}".format(model[0].bias.flatten()))

Starting weights: tensor([3.0000], grad_fn=<ReshapeAliasBackward0>)
Starting bias: Parameter containing:
tensor([5.0000], requires_grad=True)


## Sovling OR problem with a single perceptron

| x1 | x2 | y |
|:--:|:--:|:-:|
|  0 |  0 | 0 |
|  0 |  1 | 1 |
|  1 |  0 | 1 |
|  1 |  1 | 1 |

In [15]:
X = torch.FloatTensor([[0, 0], [0, 1], [1, 0], [1, 1]]).to(device)
Y = torch.FloatTensor([[0], [1], [1], [1]]).to(device)

In [3]:
# Single neuron Perceptron model
model = nn.Sequential(
            nn.Linear(2, 1, bias=True), 
            nn.Sigmoid()
        ).to(device)

In [4]:
criterion = nn.MSELoss()
optimizer = optim.SGD(model.parameters(), lr=0.1)

In [5]:
for step in range(5000):
    pred = model(X)
    loss = criterion(pred, Y)
    
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()
    
    if step % 200==0:
        print('step:', step, " loss:", loss.item())

step: 0  loss: 0.15306387841701508
step: 200  loss: 0.09753914177417755
step: 400  loss: 0.07150579988956451
step: 600  loss: 0.0548553392291069
step: 800  loss: 0.04369859769940376
step: 1000  loss: 0.035865042358636856
step: 1200  loss: 0.03014693595468998
step: 1400  loss: 0.025836311280727386
step: 1600  loss: 0.022497672587633133
step: 1800  loss: 0.01985195465385914
step: 2000  loss: 0.0177138764411211
step: 2200  loss: 0.01595669612288475
step: 2400  loss: 0.014491286128759384
step: 2600  loss: 0.01325354166328907
step: 2800  loss: 0.01219630241394043
step: 3000  loss: 0.011284248903393745
step: 3200  loss: 0.010490469634532928
step: 3400  loss: 0.009794162586331367
step: 3600  loss: 0.009179039858281612
step: 3800  loss: 0.008632124401628971
step: 4000  loss: 0.008143034763634205
step: 4200  loss: 0.007703353185206652
step: 4400  loss: 0.007306162267923355
step: 4600  loss: 0.006945773493498564
step: 4800  loss: 0.006617441773414612


#### [TODO] show graph

In [6]:
pred = model(X)
print(pred)

tensor([[0.1200],
        [0.9264],
        [0.9263],
        [0.9991]], grad_fn=<SigmoidBackward0>)


[TODO] add thresholding

## Solving AND problem with a single perceptron

| x1 | x2 | y |
|:--:|:--:|:-:|
|  0 |  0 | 0 |
|  0 |  1 | 0 |
|  1 |  0 | 0 |
|  1 |  1 | 1 |

#### [TODO] Format of data for batching

In [16]:
X = torch.FloatTensor([[0, 0], [0, 1], [1, 0], [1, 1]]).to(device)
Y = torch.FloatTensor([[0], [0], [0], [1]]).to(device)

In [19]:
# Perceptron model
model = nn.Sequential(
            nn.Linear(2, 1, bias=True), 
            nn.Sigmoid()
        ).to(device)

In [20]:
criterion = nn.MSELoss()
optimizer = optim.SGD(model.parameters(), lr=0.1)

In [21]:
for step in range(5000):
    pred = model(X)
    loss = criterion(pred, Y)
    
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()
    
    if step % 1000==0:
        print('step:', step, " loss:", loss.item())

step: 0  loss: 0.20026694238185883
step: 1000  loss: 0.05582744628190994
step: 2000  loss: 0.031272247433662415
step: 3000  loss: 0.020983580499887466
step: 4000  loss: 0.01551942341029644


In [22]:
pred = model(X)
print(pred)

tensor([[0.0030],
        [0.1191],
        [0.1191],
        [0.8571]], grad_fn=<SigmoidBackward0>)


## Solving XOR problem with a single perceptron

| x1 | x2 | y |
|:--:|:--:|:-:|
|  0 |  0 | 0 |
|  0 |  1 | 1 |
|  1 |  0 | 1 |
|  1 |  1 | 0 |

In [23]:
X = torch.FloatTensor([[0, 0], [0, 1], [1, 0], [1, 1]]).to(device)
Y = torch.FloatTensor([[0], [1], [1], [0]]).to(device)

In [24]:
# Perceptron model
model = nn.Sequential(
            nn.Linear(2, 1, bias=True), 
            nn.Sigmoid()
        ).to(device)

In [25]:
criterion = nn.MSELoss()
optimizer = optim.SGD(model.parameters(), lr=0.1)

In [26]:
for step in range(5000):
    pred = model(X)
    loss = criterion(pred, Y)
    
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()
    
    if step % 1000==0:
        print('step:', step, " loss:", loss.item())

step: 0  loss: 0.28076133131980896
step: 1000  loss: 0.25000685453414917
step: 2000  loss: 0.25000008940696716
step: 3000  loss: 0.2499999850988388
step: 4000  loss: 0.2499999850988388


In [16]:
pred = model(X)
print(pred)

tensor([[0.5000],
        [0.5000],
        [0.5000],
        [0.5000]], grad_fn=<SigmoidBackward0>)


In [20]:
# Perceptron model
model = nn.Sequential(
            nn.Linear(2, 2, bias=True),
            nn.Sigmoid(),
            nn.Linear(2, 1, bias=True), 
            nn.Sigmoid()
        ).to(device)

In [21]:
criterion = nn.BCELoss()
optimizer = optim.SGD(model.parameters(), lr=0.1)

In [22]:
for step in range(5000):
    pred = model(X)
    loss = criterion(pred, Y)
    
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()
    
    if step % 2000==0:
        print('step:', step, " loss:", loss.item())

step: 0  loss: 0.7511292099952698
step: 2000  loss: 0.679911732673645
step: 4000  loss: 0.4593662619590759


In [23]:
pred = model(X)
print(pred)

tensor([[0.0521],
        [0.9203],
        [0.4954],
        [0.5314]], grad_fn=<SigmoidBackward0>)
