## Sum Problem using Perception

In [43]:
import torch
import torch.nn as nn
device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")

In [44]:
X = torch.tensor([[1,2],[2,3],[3,4],[4,5]],dtype=torch.float32)
Y = torch.tensor([[3],[5],[7],[9]],dtype=torch.float32)
print(X)
print(Y)

tensor([[1., 2.],
        [2., 3.],
        [3., 4.],
        [4., 5.]])
tensor([[3.],
        [5.],
        [7.],
        [9.]])


In [45]:
model = nn.Sequential(
    nn.Linear(2,1,bias=True)
).to(device)

In [46]:
model

Sequential(
  (0): Linear(in_features=2, out_features=1, bias=True)
)

In [47]:
model[0].weight

Parameter containing:
tensor([[-0.5360, -0.4106]], requires_grad=True)

In [48]:
model[0].bias

Parameter containing:
tensor([-0.2168], requires_grad=True)

In [49]:
criterion = nn.MSELoss()
opt = torch.optim.SGD(model.parameters(), lr=0.01)

**Move data also into device**

In [50]:
X = X.to(device)
Y = Y.to(device)

In [51]:
device

device(type='cpu')

In [52]:
for step in range(1000):
    pred = model(X)
    loss = criterion(pred, Y)
    opt.zero_grad()
    loss.backward()
    opt.step()
    if step % 100 == 0:
        print(step, loss.item())

0 91.74168395996094
100 0.013404964469373226
200 0.006734586786478758
300 0.0033834357745945454
400 0.0016998355276882648
500 0.0008539799600839615
600 0.0004290445358492434
700 0.0002155479451175779
800 0.00010828982340171933
900 5.440173845272511e-05


In [53]:
pred = model(X)
print(pred)

tensor([[3.0083],
        [5.0039],
        [6.9995],
        [8.9951]], grad_fn=<AddmmBackward0>)


**Predict on new input**

In [54]:
new_inp = torch.tensor([[5,6],[6,7]],dtype=torch.float32).to(device)
pred = model(new_inp)
pred

tensor([[10.9907],
        [12.9863]], grad_fn=<AddmmBackward0>)

In [57]:
pred_arr = pred.detach().cpu().numpy()
pred_arr

array([[10.99067 ],
       [12.986253]], dtype=float32)

In [60]:
import numpy as np
assert np.round(pred_arr).all() == np.array([[11],[13]]).all(), "Wrong answer, train again!"